config/routes.rb
WhereToEat::Application.routes.draw do

  resources :check_ins

  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :restaurants

  resources :item_reviews

  resources :items

  resources :menus

  resources :restaurant_reviews

  resources :users

  get "home", to: "home#index"
  post "home", to: "home#index"
  post "home/filter", to: "home#filter", as: :filter
  patch "users/:id/add_coordinates/", to: "users#add_coordinates", as: :add_coordinates
  patch "users/add_check_in/:id", to: "users#add_check_in", as: :add_check_in
  post "users/send_meetup_email/", to: "users#send_meetup_email", as: :meetup_email

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	@restaurants = Restaurant.generate_list(current_user.latitude, current_user.longitude)
    @check_ins = CheckIn.all
  	puts @restaurants.inspect
  	render "home/index"
  end

  def filter
  	if params[:filter] == 'price'
  		puts 'price'
  		@restaurants = Restaurant.by_price
  		puts @restaurants
  	elsif params[:filter] == 'distance'
  		puts 'distance'
  		@restaurants = Restaurant.by_distance(params[:latitude], params[:longitude])
  	elsif params[:filter] == 'waiting_time'
  		puts 'waiting_time'
  		@restaurants = Restaurant.by_waiting_time
  	elsif params[:filter] == 'rating'
  		puts 'rating'
  		@restaurants = Restaurant.by_rating
  	end
	respond_to do |format|
		format.json {render json: @restaurants.map {|r| r.to_json}}
	end
  end
end

app/views/home/_home_feed.html.haml
%div.list-group
- @check_ins.each do |check_in|

  %div.list-group-item.feed-item{:href => 'user/' + check_in.user_id.to_s, :class => "#"}
    %a.circle
      = image_tag(check_in.user.avatar.url, height: '32', width: '32')
    %a
      = link_to 'Message', meetup_email_path(:sender_id => @current_user, :receiver_id => check_in.user), :method => :post
      %span.glyphicon.glyphicon-envelope
    .title
      %h6= check_in.user.name + " checked into " + check_in.restaurant.name + " " + time_ago_in_words(check_in.created_at) + " ago"
      - if check_in.comment.present?
        %h6= check_in.message
/assets/


/, :style => "background-image: linear-gradient(to right, rgba(0, 0, 0, 0.75), rgba(255, 255, 255, 0)), url('/assets/asiana.jpg')"/

app/views/home/_home_filters.html.haml
%ul.nav.nav-pills
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
      Filter
      %span.caret
    %ul.dropdown-menu.centerMe
      %li
        %a#price_button{filter_type: "price"} Price
      %li
        %a#distance_button{filter_type: "distance"} Distance
      %li
        %a.filter_button{filter_type: "time"} Waiting time
      %li
        %a.filter_button{filter_type: "rating"} Rating

app/views/home/_home_restaurants.html.haml
%ul.list-group{id: 'alphabetical'}
  - @restaurants['alphabetical'].each do |restaurant|
    %a.list-group-item{:href => 'restaurants/' + restaurant.id.to_s, :class => "#{restaurant.area.downcase}"}
      .title
        %h4= restaurant.name
        - if restaurant.accepts_dinex
          %span.badge.small-badge.pull-right.payment  Dinex
        - if restaurant.accepts_cash
          %span.badge.small-badge.pull-right.payment Cash
        - if restaurant.accepts_credit
          %span.badge.small-badge.pull-right.payment  Credit
        - if restaurant.accepts_plaid_cash
          %span.badge.small-badge.pull-right.payment  Plaid Cash
        %p= restaurant.address_short
        - if current_user.latitude && current_user.longitude
          %div= restaurant.distance(current_user.latitude, current_user.longitude).round(2).to_s + " Miles"
        %span.badge= restaurant.cuisine
        %span
          %h5= '$' * restaurant.price
        %br
        %span.glyphicon.glyphicon-star.glyphicon-star-full
        %span.glyphicon.glyphicon-star.glyphicon-star-full
        %span.glyphicon.glyphicon-star.glyphicon-star-full
        %span.glyphicon.glyphicon-star.glyphicon-star-empty
        %span.glyphicon.glyphicon-star.glyphicon-star-empty
        - if restaurant
          %span.badge.pull-right.small-badge.time.open
            open now 
        - else
          %span.badge.glyphicon.glyphicon-time.pull-right.small-badge.time.closed
            closed
        %span.badge.glyphicon.glyphicon-time.pull-right.small-badge.time 10min
        %span.badge.glyphicon.glyphicon-user.pull-right.small-badge.time= restaurant.get_checked_in_users.size
    %a= link_to "Check In", add_check_in_path(current_user, :user => {:location => restaurant.id}), :method => :patch, class: "btn btn-primary btn-warning btn-xs check-in"
%ul.list-group{id: 'price'}
  - @restaurants['price'].each do |restaurant|
    %a.list-group-item{:href => 'restaurants/' + restaurant.id.to_s, :class => "#{restaurant.area.downcase}"}
      .title
        %h4= restaurant.name
        - if restaurant.accepts_dinex
          %span.badge.small-badge.pull-right.payment  Dinex
        - if restaurant.accepts_cash
          %span.badge.small-badge.pull-right.payment Cash
        - if restaurant.accepts_credit
          %span.badge.small-badge.pull-right.payment  Credit
        - if restaurant.accepts_plaid_cash
          %span.badge.small-badge.pull-right.payment  Plaid Cash
        %p= restaurant.address_short
        - if current_user.latitude && current_user.longitude
          %div= restaurant.distance(current_user.latitude, current_user.longitude).round(2).to_s + " Miles"
        %span.badge= restaurant.cuisine
        %span
          %h5= '$' * restaurant.price
        %br
        %span.glyphicon.glyphicon-star.glyphicon-star-full
        %span.glyphicon.glyphicon-star.glyphicon-star-full
        %span.glyphicon.glyphicon-star.glyphicon-star-full
        %span.glyphicon.glyphicon-star.glyphicon-star-empty
        %span.glyphicon.glyphicon-star.glyphicon-star-empty
        - if restaurant
          %span.badge.pull-right.small-badge.time
            Open Now
        - else
          %span.badge.glyphicon.glyphicon-time.pull-right.small-badge.time
            Closed
        %span.badge.glyphicon.glyphicon-time.pull-right.small-badge.time 10min
        %span.badge.glyphicon.glyphicon-user.pull-right.small-badge.time= restaurant.get_checked_in_users.size
    %a= link_to "Check In", add_check_in_path(current_user, :user => {:location => restaurant.id}), :method => :patch, class: "btn btn-primary btn-warning btn-xs check-in"
%ul.list-group{id: 'distance'}
  - @restaurants['by_distance'].each do |restaurant|
    %a.list-group-item{:href => 'restaurants/' + restaurant.id.to_s, :class => "#{restaurant.area.downcase}"}
      .title
        %h4= restaurant.name
        - if restaurant.accepts_dinex
          %span.badge.small-badge.pull-right.payment  Dinex
        - if restaurant.accepts_cash
          %span.badge.small-badge.pull-right.payment Cash
        - if restaurant.accepts_credit
          %span.badge.small-badge.pull-right.payment  Credit
        - if restaurant.accepts_plaid_cash
          %span.badge.small-badge.pull-right.payment  Plaid Cash
        %p= restaurant.address_short
        - if current_user.latitude && current_user.longitude
          %div= restaurant.distance(current_user.latitude, current_user.longitude).round(2).to_s + " Miles"
        %span.badge= restaurant.cuisine
        %span
          %h5= '$' * restaurant.price
        %br
        %span.glyphicon.glyphicon-star.glyphicon-star-full
        %span.glyphicon.glyphicon-star.glyphicon-star-full
        %span.glyphicon.glyphicon-star.glyphicon-star-full
        %span.glyphicon.glyphicon-star.glyphicon-star-empty
        %span.glyphicon.glyphicon-star.glyphicon-star-empty
        - if restaurant
          %span.badge.pull-right.small-badge.time
            Open Now
        - else
          %span.badge.glyphicon.glyphicon-time.pull-right.small-badge.time
            Closed
        %span.badge.glyphicon.glyphicon-time.pull-right.small-badge.time 10min
        %span.badge.glyphicon.glyphicon-user.pull-right.small-badge.time= restaurant.get_checked_in_users.size
    %a= link_to "Check In", add_check_in_path(current_user, :user => {:location => restaurant.id}), :method => :patch, class: "btn btn-primary btn-warning btn-xs check-in"

app/views/home/index.html.erb
<head>
	<script src="http://maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry", type: "text/javascript"></script>
	<body>
		<div class="container">
			<div class="navbar navbar-default navbar-fixed-top">
			    <div class="navbar-header pull-left">
			      <a class="navbar-brand" href="#"><h4>W2E</h4></a>
			    </div>
			    <div class="navbar-form pull-left">
			     <!-- <input type="text" class="form-control col-lg-8 " placeholder="Search" id="search">
			     -->
			    </div>
			    <div class="pull-right">
			    	<%= link_to '<span class="glyphicon glyphicon-cog"></span>'.html_safe, edit_user_path(current_user), class: "btn btn-nav"%>
			    </div>
			</div>
			    <!--<div class="navbar-form pull-right">
			    	<%#= link_to 'Add Restaurant', new_restaurant_path, class: 'btn btn-default' %>
			    </div>
			    -->
			</div>
			<div class="col-md-8">
				<%= render file: 'restaurants/index' %>
				<%= yield :javascripts %>
			</div>
		</div>
	</body>
</head>