config/routes.rb
WhereToEat::Application.routes.draw do

  resources :check_ins

  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :restaurants

  resources :item_reviews

  resources :items

  resources :menus

  resources :restaurant_reviews

  resources :users

  get "home", to: "home#index"
  post "home", to: "home#index"
  post "home/filter", to: "home#filter", as: :filter
  patch "users/:id/add_coordinates/", to: "users#add_coordinates", as: :add_coordinates
  patch "users/add_check_in/:id", to: "users#add_check_in", as: :add_check_in
  post "users/send_meetup_email/", to: "users#send_meetup_email", as: :meetup_email

end

app/controllers/item_reviews_controller.rb
class ItemReviewsController < ApplicationController
  before_action :set_item_review, only: [:show, :edit, :update, :destroy]

  # GET /item_reviews
  # GET /item_reviews.json
  def index
    @item_reviews = ItemReview.all
  end

  # GET /item_reviews/1
  # GET /item_reviews/1.json
  def show
  end

  # GET /item_reviews/new
  def new
    @item_review = ItemReview.new
  end

  # GET /item_reviews/1/edit
  def edit
  end

  # POST /item_reviews
  # POST /item_reviews.json
  def create
    @item_review = ItemReview.new(item_review_params)

    respond_to do |format|
      if @item_review.save
        format.html { redirect_to @item_review, notice: 'Item review was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item_review }
      else
        format.html { render action: 'new' }
        format.json { render json: @item_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_reviews/1
  # PATCH/PUT /item_reviews/1.json
  def update
    respond_to do |format|
      if @item_review.update(item_review_params)
        format.html { redirect_to @item_review, notice: 'Item review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_reviews/1
  # DELETE /item_reviews/1.json
  def destroy
    @item_review.destroy
    respond_to do |format|
      format.html { redirect_to item_reviews_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_review
      @item_review = ItemReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_review_params
      params.require(:item_review).permit(:restaurant_id, :user_id, :item_id, :review, :rating, :date)
    end
end

app/helpers/item_reviews_helper.rb
module ItemReviewsHelper
end

app/views/item_reviews/_form.html.erb
<%= form_for(@item_review) do |f| %>
  <% if @item_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_review.errors.count, "error") %> prohibited this item_review from being saved:</h2>

      <ul>
      <% @item_review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :restaurant_id %><br>
    <%= f.text_field :restaurant_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.text_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :review %><br>
    <%= f.text_field :review %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_reviews/edit.html.erb
<h1>Editing item_review</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_review %> |
<%= link_to 'Back', item_reviews_path %>

app/views/item_reviews/index.html.erb
<h1>Listing item_reviews</h1>

<table>
  <thead>
    <tr>
      <th>Restaurant</th>
      <th>User</th>
      <th>Item</th>
      <th>Review</th>
      <th>Rating</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @item_reviews.each do |item_review| %>
      <tr>
        <td><%= item_review.restaurant %></td>
        <td><%= item_review.user %></td>
        <td><%= item_review.item %></td>
        <td><%= item_review.review %></td>
        <td><%= item_review.rating %></td>
        <td><%= item_review.date %></td>
        <td><%= link_to 'Show', item_review %></td>
        <td><%= link_to 'Edit', edit_item_review_path(item_review) %></td>
        <td><%= link_to 'Destroy', item_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item review', new_item_review_path %>

app/views/item_reviews/new.html.erb
<h1>New item_review</h1>

<%= render 'form' %>

<%= link_to 'Back', item_reviews_path %>

app/views/item_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Restaurant:</strong>
  <%= @item_review.restaurant %>
</p>

<p>
  <strong>User:</strong>
  <%= @item_review.user %>
</p>

<p>
  <strong>Item:</strong>
  <%= @item_review.item %>
</p>

<p>
  <strong>Review:</strong>
  <%= @item_review.review %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @item_review.rating %>
</p>

<p>
  <strong>Date:</strong>
  <%= @item_review.date %>
</p>

<%= link_to 'Edit', edit_item_review_path(@item_review) %> |
<%= link_to 'Back', item_reviews_path %>